name: dino_flutter_example
description: An example of using the dino_flutter package.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  dino: ^1.0.0-pre.1
  dino_flutter: ^1.0.0-pre.1
  flutter:
    sdk: flutter
