name: dino
description: A Dart dependency injection library aimed to be flexible, predictable and easy to use.
version: 1.0.0-pre.1
repository: https://github.com/Exeteres/dino

environment:
  sdk: ^3.0.0

dev_dependencies:
  coverage: ^1.0.0
  full_coverage: 0.0.3
  test: ^1.21.1
