name: dino_generator
description: An optional static code generator for the dino library.
version: 1.0.0-pre.4
repository: https://github.com/Exeteres/dino

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  code_builder: ^4.3.0
  dino: ^1.0.0-pre.1
  source_gen: ^1.2.6

dev_dependencies:
  build_runner: ^2.3.2
  build_test: ^2.1.5
  coverage: ^1.0.0
  dart_style: ^2.0.3
  full_coverage: 0.0.3
  test: ^1.21.1
