name: dino_flutter
description: An integration of the dino package with the flutter framework.
version: 1.0.0-pre.1
repository: https://github.com/Exeteres/dino

environment:
  sdk: ^3.0.0

dependencies:
  dino: ^1.0.0-pre.1
  flutter:
    sdk: flutter
dev_dependencies:
  coverage: ^1.0.0
  test: ^1.21.1
